-- MySQL Script generated by MySQL Workbench
-- Mon 30 Nov 2015 07:22:05 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flight
-- -----------------------------------------------------
-- flight ticket order administration system

-- -----------------------------------------------------
-- Schema flight
--
-- flight ticket order administration system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flight` DEFAULT CHARACTER SET utf8 ;
USE `flight` ;

-- -----------------------------------------------------
-- Table `flight`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`user` (
  `username` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `point` INT NULL DEFAULT 0,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));


-- -----------------------------------------------------
-- Table `flight`.`airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`airplane` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstclass` INT NOT NULL,
  `economyclass` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`flight` (
  `id` INT NOT NULL,
  `startplace` VARCHAR(100) NOT NULL,
  `starttime` TIME NOT NULL,
  `arrivalplace` VARCHAR(100) NOT NULL,
  `arrivaltime` TIME NOT NULL,
  `idairplance` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idairplane_idx` (`idairplance` ASC),
  INDEX `place_idx` (`startplace` ASC, `arrivalplace` ASC),
  CONSTRAINT `fk_idairplane`
    FOREIGN KEY (`idairplance`)
    REFERENCES `flight`.`airplane` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`ticket` (
  `idflight` INT NOT NULL,
  `flightdate` DATE NOT NULL,
  `firstcount` INT NOT NULL,
  `firstprice` DOUBLE NOT NULL,
  `economycount` INT NOT NULL,
  `economyprice` DOUBLE NOT NULL,
  INDEX `fk_idflight_idx` (`idflight` ASC),
  PRIMARY KEY (`idflight`, `flightdate`),
  CONSTRAINT `fk_idflight`
    FOREIGN KEY (`idflight`)
    REFERENCES `flight`.`flight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`order` (
  `username` VARCHAR(32) NOT NULL,
  `flightdate` DATE NOT NULL,
  `idflight` INT NOT NULL,
  `ordertime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NULL DEFAULT 0,
  INDEX `username_idx` (`username` ASC),
  INDEX `fk_idflight_idx` (`idflight` ASC),
  PRIMARY KEY (`username`, `flightdate`, `idflight`),
  INDEX `fk_flightdate_idx` (`flightdate` ASC),
  CONSTRAINT `fk_username`
    FOREIGN KEY (`username`)
    REFERENCES `flight`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flightdate`
    FOREIGN KEY (`flightdate`)
    REFERENCES `flight`.`ticket` (`flightdate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idflight`
    FOREIGN KEY (`idflight`)
    REFERENCES `flight`.`ticket` (`idflight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `flight` ;

-- -----------------------------------------------------
-- Placeholder table for view `flight`.`ticketflight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`ticketflight` (`id` INT, `startplace` INT, `starttime` INT, `arrivalplace` INT, `arrivaltime` INT, `flightdate` INT, `firstcount` INT, `firstprice` INT, `economycount` INT, `economyprice` INT);

-- -----------------------------------------------------
-- Placeholder table for view `flight`.`orderticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight`.`orderticket` (`username` INT, `flightdate` INT, `idflight` INT, `ordertime` INT, `status` INT);

-- -----------------------------------------------------
-- View `flight`.`ticketflight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`ticketflight`;
USE `flight`;
CREATE  OR REPLACE VIEW `ticketflight` AS
    SELECT 
        `id`,
        `startplace`,
        `starttime`,
        `arrivalplace`,
        `arrivaltime`,
        `flightdate`,
        `firstcount`,
        `firstprice`,
        `economycount`,
        `economyprice`
    FROM
        `flight`,
        `ticket`
    WHERE
        `flight`.`id` = `ticket`.`idflight`;

-- -----------------------------------------------------
-- View `flight`.`orderticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`orderticket`;
USE `flight`;
CREATE  OR REPLACE VIEW `orderticket` AS
    SELECT 
        *
    FROM
        `order`,
        `ticketflight`
    WHERE
        `order`.`flightdate` = `ticketflight`.`flightdate`
            AND `order`.`idflight` = `ticketflight`.`idflight`;
CREATE USER 'flight' IDENTIFIED BY 'flight';

GRANT ALL ON `flight`.* TO 'flight';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
