-- MySQL Script generated by MySQL Workbench
-- Mon 04 Jan 2016 11:39:13 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flightweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flightweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flightweb` DEFAULT CHARACTER SET utf8 ;
USE `flightweb` ;

-- -----------------------------------------------------
-- Table `flightweb`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightweb`.`flight` ;

CREATE TABLE IF NOT EXISTS `flightweb`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flightid` VARCHAR(45) NOT NULL,
  `flightdate` DATE NOT NULL,
  `startplace` VARCHAR(45) NOT NULL,
  `arrivalplace` VARCHAR(45) NOT NULL,
  `starttime` TIME NOT NULL,
  `arrivaltime` TIME NOT NULL,
  `firstcount` INT NULL,
  `economycount` INT NULL,
  `firstprice` DOUBLE NULL,
  `economyprice` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_flight_id_date` (`flightid` ASC, `flightdate` ASC),
  INDEX `search_index` (`flightdate` ASC, `startplace` ASC, `arrivalplace` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flightweb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightweb`.`order` ;

CREATE TABLE IF NOT EXISTS `flightweb`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `flightid` VARCHAR(45) NOT NULL,
  `flightdate` DATE NOT NULL,
  `startplace` VARCHAR(45) NOT NULL,
  `arrivalplace` VARCHAR(45) NOT NULL,
  `starttime` TIME NOT NULL,
  `arrivaltime` TIME NOT NULL,
  `isfirst` TINYINT(1) NOT NULL DEFAULT 0,
  `price` DOUBLE NOT NULL,
  `paid` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `search_history` (`username` ASC, `flightdate` ASC))
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO flightweb;
 DROP USER flightweb;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'flightweb' IDENTIFIED BY 'flightweb';

GRANT ALL ON `flightweb`.* TO 'flightweb';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
